### ISSUE TITLE
Lot of output chunks has no voice with only noise

### ISSUE THREAD

**Issue by Mutturaj-BEL** [LennyBijan/FinetuningWhisperWithMedium#2]
After i completed transcribing(openai/whisper-large-v3) my audio set using your code.
I can see lot of chunks showing text as 'Thank you',,these audio chunk has only noise
Example:
20240613_044819_to_20240613_055530-S-_chunk_0007.wav, Thank you.
20240613_044819_to_20240613_055530-S-_chunk_0008.wav, Thank you.
20240613_044819_to_20240613_055530-S-_chunk_0009.wav, Thank you.

Any tweak where i can only choose the files which has voice and discard the files with only noise

And input only files with voice to transcribing  pipeline

**Comment by LennyBijan** [comment]
> After i completed transcribing(openai/whisper-large-v3) my audio set using your code.
> 
> I can see lot of chunks showing text as 'Thank you',,these audio chunk has only noise
> 
> Example:
> 
> 20240613_044819_to_20240613_055530-S-_chunk_0007.wav, Thank you.
> 
> 20240613_044819_to_20240613_055530-S-_chunk_0008.wav, Thank you.
> 
> 20240613_044819_to_20240613_055530-S-_chunk_0009.wav, Thank you.
> 
> 
> 
> Any tweak where i can only choose the files which has voice and discard the files with only noise
> 
> 
> 
> And input only files with voice to transcribing  pipeline


Hey, "Pipeline_Chunk" has VAD (voice activity detection) which should filter out all the chunks without noise. I'd suggest going back to the audio files as that's where the issue stems from most likely.

For example, search which audio file this snippet belongs to originally and listen to the files after successfully chunking. Do you have multiple snippets saying "thank you"? If yes then something went wrong with the VAD. 

The chunks should also at least be 5s after completing chunking, is that the case? 

You can try tweaking some of the settings for VAD as they currently work with a standard deviation of energy and ZCR as thresholds for voice.

**Comment by LennyBijan** [comment]
You can also try making the overlap smaller or removing it all-together to see if that fixes the issue

**Comment by Mutturaj-BEL** [comment]
After reducing overlap  to 20 ms .. there is a improvement.
But still still lot of chunks has noise
I have applied silver-VAD to the chunks and only extracted chunks having voice.
Results are better and only chunks with speech are extracted.

**Comment by LennyBijan** [comment]
glad you were able to resolve the issue with a little workaround 👍🏻
